#  Name of workflow
name: Deploy
# Trigger workflow on all pull requests
on:
     push:
          branches:
               - main

# Jobs to carry out
jobs:
     build:
          runs-on: ubuntu-latest
          steps:
               - uses: actions/checkout@v2
               - uses: akhileshns/heroku-deploy@v3.12.11
                 with:
                      heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                      heroku_app_name: "gh-actions-demo"
                      heroku_email: "skhatiwada@instructors.2u.com"
